### PR TITLE
Accessibility touchups

### LINKED ISSUE #55: [Bug] A few accessibility issues on the landing page
### Describe the bug

Hi! https://temporal.io is a fantastic landing page and I love it 😄.

I ran the [aXe dev tools](https://www.deque.com/axe/devtools) on it and it pointed out a few accessibility issues that I could confirm do have impact.

### To Reproduce

1. Install the aXe browser extension, such as the [Chrome one](https://chrome.google.com/webstore/detail/axe-devtools-web-accessib/lhdoppojpmngadmnindnejefpokejbdd?hl=en-US)
2. Run it on the page
3. See, within the list of results, the 4 that are not marked as needing review

### Expected behavior

No accessibility issues.

### Screenshots/Terminal output

Screenshot of several aXe failure groups

### Versions

- OS: [e.g. Mac, Windows, Linux] N/A
- Temporal Version [e.g. 1.7.0?] N/A
- Are you using Docker or Kubernetes or building Temporal from source? N/A

### Additional context

I'll send a PR in a quick bit 😄

### PR DESCRIPTION
**Pull request by JoshuaKGoldberg**
## What was changed
Fixes up a few assorted accessibility issues. Attempts to keep the pages generally visually the same as they were before, except where noted (mostly for color contrast reasons).

Explanations & any visual changes marked inline.

## Why?
Accessibility! 🦾💖 

## Checklist

1. Closes #55 

2. How was this tested:
I checked screen resolutions on example mobile (400px), tablet (800px), and desktop (1600px) widths.

### CODE REVIEW

File: components/Hero.js [hunk 1]
```diff
@@ -11,7 +10,6 @@ export default function Hero() {
     <div>
       <Banner />
       <section className="container mx-auto p-4">
-        <Nav />
```
Comment (JoshuaKGoldberg) [inline components/Hero.js:14]: The `<Nav />` component contains the `header` region of the page. This `Hero` component exists within the area of the page that would be contained by the `main` region (`<main>`). Putting regions within regions doesn't make sense to screenreaders attempting to parse the structure & layout of the page.

Tangentially related description of regions: https://dequeuniversity.com/rules/axe/4.0/region

File: components/Nav.js [hunk 2]
```diff
@@ -24,14 +24,14 @@ export function Nav() {
           object-fit: contain;
         }
       `}</style>
-      <ul className="flex items-center justify-around md:justify-between py-4">
-        <li className="hidden md:block">
```
Comment (JoshuaKGoldberg) [inline components/Nav.js:28]: Before, the structure looked like `ul > li` for this one list item but `ul > ul > li` for the other list items. Putting any content type other than `<li>` inside a list is confusing to folks relying on screenreaders to explain the structure of the list.

https://dequeuniversity.com/rules/axe/4.3/list and https://dequeuniversity.com/rules/axe/3.5/listitem

File: components/StackedUseCases.js [hunk 3]
```diff
@@ -8,7 +8,7 @@ const Stack = ({ content, link, title }) => (
         <div className="stack__content transition-all h-full w-full p-4 bg-black rounded-lg relative border-2 flex flex-col">
           <h2 className="text-2xl tracking-wide font-bold">{title}</h2>
           <p className="flex-grow font-light my-4 text-lg">{content}</p>
-          <a className="nav-link text-center text-temporalblue">Learn More</a>
+          <div className="nav-link text-center text-temporalblue">Learn More</div>
```
Comment (JoshuaKGoldberg) [inline components/StackedUseCases.js:11]: It doesn't make much sense to have an `a` anchor within an `a`. The parent anchor already is capable of receiving focus.

File: components/StarCanvas.js [hunk 4]
```diff
@@ -153,7 +153,13 @@ const StarCanvas = () => {
     };
   }, []);
 
-  return <canvas ref={canvasRef} className="h-full w-full fixed inset-0 bg-spaceblack -z-1" />;
+  return (
+    <canvas
+      aria-hidden="true"
+      ref={canvasRef}
+      className="h-full w-full fixed inset-0 bg-spaceblack -z-1"
+    />
```
Comment (JoshuaKGoldberg) [inline components/StarCanvas.js:161]: All page content must be contained by landmarks such as `header` or `main` in order for users to be able to understand & quickly navigate between them. Since this canvas is presentational only, it makes sense to mark it as hidden so it doesn't get narrated as content outside of a landmark.

https://dequeuniversity.com/rules/axe/4.0/region

File: pages/usecases.js [hunk 5]
```diff
@@ -13,13 +14,15 @@ import Footer from '../components/Footer';
 export default function Page() {
   return (
     <Layout>
+      <Head>
+        <title>Temporal.io | Use Cases</title>
```
Comment (JoshuaKGoldberg) [inline pages/usecases.js:18]: This page was missing a unique title before. In addition to being surprisingly damaging for SEO, it also makes it harder for folks to uniquely identify the page against others in tab/window narration and bookmarks.

https://dequeuniversity.com/rules/axe/3.5/document-title

File: pages/usecases.js [hunk 6]
```diff
@@ -227,20 +245,23 @@ function Header({ id, children, extra }) {
...
           <a className="hover:underline text-blue-300 hover:text-blue-200" href={`#${id}`}>
             {children}
           </a>
         </h2>
         {extra}
       </div>
       <a
-        className="font-italic hover:underline text-blue-600 hover:text-blue-500"
-        href="#usecases-group">
+        className="font-italic hover:underline text-blue-500 hover:text-blue-500"
```
Comment (JoshuaKGoldberg) [inline pages/usecases.js:262]: `text-blue-600` is _just_ too dark against the background dark gray to be legible for all users. Folks with low vision perception and/or displays with a lot of screen glare would have a hard time seeing it.

https://dequeuniversity.com/rules/axe/3.5/color-contrast

File: styles/index.css [hunk 7]
```diff
@@ -36,7 +36,7 @@
     @apply hover:text-temporalblue transition-colors relative;
   }
   .dir-control {
-    @apply w-300 h-60 md:w-200 lg:w-300 transition-all border-2 no-underline outline-none rounded-lg text-center cursor-pointer font-bold relative flex items-center justify-center text-xl;
```
Comment (JoshuaKGoldberg) [inline styles/index.css:39]: Buttons, links, and other interactive elements should show a visual change when they're focused. Otherwise users who rely on navigating without a mouse -such as those who only use a keyboard- have a hard time knowing which element is focused at a particular time.

https://www.deque.com/blog/accessible-focus-indicators/

(this isn't statically detected by aXe, but I did notice while navigating through the page)

File: components/StackedUseCases.js (hunk 3 above)
Comment (JoshuaKGoldberg) [inline components/StackedUseCases.js:11]: It is unnecessary to have an `a` anchor within an `a`. The parent anchor already is capable of receiving focus.

File: pages/careers.js [hunk 8]
```diff
@@ -5,291 +5,318 @@ import Head from 'next/head';
...
-              href="mailto:careers@temporal.io"
-              className="underline text-blue-400 hover:text-blue-200">
-              careers@temporal.io
-            </a>{' '}
-            describing your dream job.
-          </h2>
-        </div>
-        <div className="container sm:p-8 rounded-lg mt-16 sm:ml-16">
-          <div id="lever-jobs-container">Loading... (contact us if this message persists)</div>
+    <>
```
Comment (JoshuaKGoldberg) [inline pages/careers.js:8]: Sorry for the large diff 😞, it was a little unavoidable... a page needs a `main` region so as to not be confusing for navigation, and the `<Nav />` needed to be moved out of the `main`. 

https://dequeuniversity.com/rules/axe/4.1/landmark-one-main

File: components/Banner.js [hunk 9]
```diff
@@ -4,7 +4,7 @@ export function Banner() {
   const [open, setOpen] = useLocalStorage('2yranniversary', true);
   if (!open) return null;
   return (
-    <div className="relative bg-temporalblue text-spaceblack text-center py-2">
+    <div className="relative bg-temporalblue text-spaceblack text-center py-2" role="banner">
```
Comment (JoshuaKGoldberg) [inline components/Banner.js:7]: The name of this component is accurate the the landmark of the page it belongs in.

https://dequeuniversity.com/rules/axe/4.0/region & https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/banner_role

File: components/Banner.js [hunk 10]
```diff
@@ -23,9 +23,11 @@ export function Banner() {
         </span>
         !
       </a>
-      <button onClick={() => setOpen(false)}>
+      <button
+        className="absolute right-0 top-0 mr-2 mt-3 md:mt-2 w-5 sm:w-6 h-5 sm:h-6 text-spaceblack"
+        aria-label="Close banner"
+        onClick={() => setOpen(false)}>
         <svg
-          className="absolute right-0 top-0 mr-2 mt-3 md:mt-2 w-5 sm:w-6 h-5 sm:h-6 text-spaceblack"
```
Comment (JoshuaKGoldberg) [inline components/Banner.js:28]: Putting the `absolute` class on the `svg` within the `button` instead of on the `button` itself meant the button was size 0x0. The button needs to have content so that when it's focused it has a visible focus outline.

https://www.w3.org/TR/UNDERSTANDING-WCAG20/navigation-mechanisms-focus-visible.html

(this isn't statically detected by aXe, but I did notice while navigating through the page)

File: pages/careers.js [hunk 11]
```diff
@@ -5,291 +5,318 @@ import Head from 'next/head';
...
+      <Nav />
+      <main className="pt-4 sm:pt-0">
```
Comment (JoshuaKGoldberg) [inline pages/careers.js:10]: Note that as an unintentional side effect of moving the nav and main layouts around, the page got much less padding-top. I kind of prefer it this way but I can switch it back if you prefer 😄 

<table>
<thead>
<tr>
<th>Before</th>
<th>After</th>
</tr>
</thead>
<tbody>
<tr>
<td>
Before screenshot with more top padding before main page content
</td>
<td>
After screenshot with less top padding before main page content
</td>
</tr>
</tbody>
</table>

File: components/Banner.js [hunk 12]
```diff
@@ -4,7 +4,7 @@ export function Banner() {
   const [open, setOpen] = useLocalStorage('2yranniversary', true);
   if (!open) return null;
   return (
-    <div className="relative bg-temporalblue text-spaceblack text-center py-2">
+    <header className="relative bg-temporalblue text-spaceblack text-center py-2" role="banner">
```
Comment (JoshuaKGoldberg) [inline components/Banner.js:7]: The name of this component is accurate the the landmark of the page it belongs in.

https://dequeuniversity.com/rules/axe/4.0/region & https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/banner_role

Also, weirdly, when I pushed this up as a plain `<div>` instead of any other element, all the class names were wiped out. Very confusing.

**Comment by sw-yx** [comment]
dynamite, thank you for all the fixes and the crystal clear explanation!

File: pages/careers.js (hunk 11 above)
Comment (sw-yx) [reply pages/careers.js:10]: nah its good this page hasnt gotten enough love from us.
